const eventTime=new Date('2026-10-13T19:00:00+05:00').getTime();
function tick(){let s=Math.max(0,Math.floor((eventTime-Date.now())/1000));const v=[Math.floor(s/86400),Math.floor(s/3600)%24,Math.floor(s/60)%60,s%60];['days','hours','minutes','seconds'].forEach((id,i)=>document.getElementById(id)&&(document.getElementById(id).textContent=String(v[i]).padStart(2,'0')));if(!s&&document.getElementById('countTitle'))document.getElementById('countTitle').textContent='Время праздновать!'}tick();setInterval(tick,1000);
const music=document.getElementById('music'),audio=document.getElementById('partyAudio');
function updateMusic(){music.setAttribute('aria-pressed',String(!audio.paused));music.classList.toggle('playing',!audio.paused);document.getElementById('musicLabel').textContent=audio.paused?'Right Round ▶':'Пауза ❚❚'}
async function startMusic(){try{await audio.play();}catch(e){toast('Нажми кнопку музыки ещё раз');}updateMusic();}
music.addEventListener('click',()=>{if(audio.paused)startMusic();else audio.pause();});
audio.addEventListener('play',updateMusic);audio.addEventListener('pause',updateMusic);audio.addEventListener('error',()=>toast('Не удалось загрузить музыку'));
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3000)}
if(document.getElementById('calendar'))document.getElementById('calendar').onclick=()=>{const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Ernar//Party//RU','BEGIN:VEVENT','UID:ernar-bachelor-20261013@invitation','DTSTAMP:20261009T170000Z','DTSTART:20261013T140000Z','SUMMARY:Мальчишник Ернара','DESCRIPTION:Прощай холостяцкая жизнь! Начало в 19:00 (UTC+5). Место сообщим отдельно.','END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([ics],{type:'text/calendar;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='ernar-13-october.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Приглашение для календаря скачано')};
if(document.getElementById('celebrate'))document.getElementById('celebrate').onclick=()=>{toast('За Ернара! До встречи 13 октября 🔥');if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<60;i++){const p=document.createElement('i');p.className='confetti';p.style.left=Math.random()*100+'vw';p.style.background=['#ff3838','#f1e9df','#a42929'][i%3];p.style.setProperty('--drift',(Math.random()-.5)*300+'px');p.style.animationDelay=Math.random()*.6+'s';document.body.append(p);setTimeout(()=>p.remove(),3400)}};

const sceneMusic=document.getElementById('sceneMusic');if(sceneMusic)sceneMusic.addEventListener('click',()=>{if(audio.paused)startMusic();});
